# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_uf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unityfoment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
